### PR TITLE
[WIP]Added the ability to pass keyword args from python, fixes #78

### LINKED ISSUE #78: nim keyword arguments in python
Right now I cant pass keyword args from python to nim proc.
```nim
import nimpy
import strformat

proc greet(name: string, greeting: string = "hi"): string {.exportpy.} =
    ## Say a greeting to a name
    return &"{greeting} {name}"
```
python throws the following when trying to pass keyword args
```python
>>> import test
>>> test.greet(name="bob")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: greet() takes no keyword arguments
```
The help message also does not reflect the arguments:
```python
>>> help(test.greet)
Help on built-in function greet in module test:

greet(...)
    Say a greeting to a person
```

### PR DESCRIPTION
**Pull request by BontaVlad**
fixes #78 
This is my first adventure with nim macros, if you know how to clean up the code feel free to hit me with any suggestions.

### CODE REVIEW

File: nimpy.nim [hunk 1]
```diff
@@ -746,84 +761,96 @@ proc pythonException(e: ref Exception): PPyObject =
...
         let argIdent = newIdentNode("arg" & $a.idx & $a.name)
+        argsNames.add($a.name)
         if a.typ.kind == nnkEmpty:
           error("Typeless arguments are not supported by nimpy: " & $a.name, a.name)
         # XXX: The newCall("type", a.typ) should be just `a.typ` but compilation fails. Nim bug?
-        pyValueVarSection.add(newIdentDefs(argIdent, newCall(bindSym"valueTypeForArgType", newCall("type", a.typ))))
         if a.default.kind != nnkEmpty:
-            parseArgsStmts.add(newCall(bindSym"parseArg", argsTupleIdent, newLit(a.idx), a.default, argIdent))
+          # if we have a default, set it during var declaration
+          pyValueVarSection.add(newIdentDefs(argIdent, newCall(bindSym"valueTypeForArgType", newCall("type", a.typ)), a.default))
```
Comment (BontaVlad) [inline nimpy.nim]: Wrong indentation.

File: nimpy.nim [hunk 2]
```diff
@@ -746,84 +761,96 @@ proc pythonException(e: ref Exception): PPyObject =
...
+        numArgsReq = 0
+        argsNames = newSeq[string]()
 
-    var numArgs = 0
-    var numArgsReq = 0
     for a in prc.arguments:
         let argIdent = newIdentNode("arg" & $a.idx & $a.name)
+        argsNames.add($a.name)
         if a.typ.kind == nnkEmpty:
           error("Typeless arguments are not supported by nimpy: " & $a.name, a.name)
```
Comment (BontaVlad) [inline nimpy.nim]: wrong indentation

File: nimpy.nim [hunk 3]
```diff
@@ -746,84 +761,96 @@ proc pythonException(e: ref Exception): PPyObject =
...
+        nameLit = newLit($prc)
     result = quote do:
-        if verifyArgs(`argsTuple`, `argsLen`, `argsLenReq`, `nameLit`):
-            when `prc` is proc {.closure.}:
-                # When proc is a closure, we don't need to prevent inlining,
-                # because updateStackBottom must have been called at this point.
-                let `argsTupleIdent` {.used.} = `argsTuple`
+        # did we get enought arguments? or correct arguments names?
+        if not verifyArgs(`argsTuple`, `kwargsDict`, `argsLen`, `argsLenReq`, `argsNames`, `nameLit`):
+          return PPyObject(nil)
```
Comment (BontaVlad) [inline nimpy.nim]: Wrong indentation.

File: nimpy.nim [hunk 4]
```diff
@@ -778,11 +795,13 @@ macro callNimProcWithPythonArgs(prc: typed, argsTuple: PPyObject, kwargsDict: PP
     var
         numArgs = 0
         numArgsReq = 0
-        argsNames = newSeq[string]()
+        argName: cstring
```
Comment (BontaVlad) [inline nimpy.nim]: without `var` argNames will contain garbage.

File: tests/tnimfrompy.py [hunk 5]
```diff
@@ -8,10 +9,29 @@
 greet_args = ("world", )
 greet_kwargs = {'greeting': "Hello", }
 assert(s.greet(*greet_args, **greet_kwargs) == "Hello, world!")
+
+try:
+    s.greet()
+except TypeError as e:
+    if sys.version_info[0] == 2:
+        assert("TypeError('greet() takes exactly 2 arguments (0 given)',)" in repr(e))
```
Comment (BontaVlad) [inline tests/tnimfrompy.py]: Not sure if I did something wrong or it's a normal diff between py2 and py3

Comment (yglukhov) [reply tests/tnimfrompy.py]: I think you can just check `greet() takes exactly 2 arguments (0 given)` in `repr(e)` to avoid version branching. Also add `doAssert(false)` at the end of the `try` block to make sure the exception happens.

File: nimpy.nim [hunk 6]
```diff
@@ -685,27 +689,57 @@ proc nimTupleToPy[T](o: T): PPyObject =
...
+
     if not result:
         GC_disable()
         pyLib.PyErr_SetString(pyLib.PyExc_TypeError, funcName & "() takes exactly " & $argsLen & " arguments (" & $sz & " given)")
         GC_enable()
+        result = false
+
+    if not kwargsDict.isNil:
+        for k in keys(kwargsDict):
+            if $k notin argNames:
```
Comment (yglukhov) [inline nimpy.nim]: This needs some more work.
1. `$` allocates and can trigger GC.
2. `argNames[req_idx..^1]` allocates and can trigger GC.

**Comment by yglukhov** [comment]
There are still allocations in `dictKeys`, but fine, i'll fix it later.
